apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: channel-to-log
spec:
  source:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: Channel
      name: messages
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: log-sink
    properties:
      showStreams: "true"
