apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: beer-to-channel
spec:
  source:
    properties:
      period: 10000
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: beer-source
  steps:
  - properties:
      field: name
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: extract-field-action
  - properties:
      field: text
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: hoist-field-action
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: Channel
      name: messages
